<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MatakuliahSI extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $m = [
            'kode' => [
                'KU101',
                'KU102',
                'SI101',
                'SI102',
                'SI103',
                'SI104',
                'SI105',
                'SI106',
                'SI18101',
                'SI18102',
                'SI18103',
                'SI18104',
                'SI18105',
                'SI18106',
                'SI18107',
                'SI18108',
                'SI18121',
                'SI18122',
                'SI18123',
                'KU201',
                'KU202',
                'SI18201',
                'SI18202',
                'SI18203',
                'SI18204',
                'SI18205',
                'SI18206',
                'SI18207',
                'SI201',
                'SI202',
                'SI203',
                'SI204',
                'SI205',
                'KU301',
                'SI301',
                'SI302',
                'SI303',
                'SI304',
                'SI305',
                'SI306',
                'KU401',
                'SI401',
                'SI402',
                'SI403',
                'SI404',
                'SI405',
                'SI406',
                'SI407',
                'ET20501',
                'SI20501',
                'SI20502',
                'SI20503',
                'SI20511',
                'SI20512',
                'SI20513',
                'SI20514',
                'SI20515',
                'SI20521',
                'SI20522',
                'SI20523',
                'SI20524',
                'SI20661',
                'SI20662',
                'SI20663',
                'KM20611',
                'KM20612',
                'KM20613',
                'KM20614',
                'KM20615',
                'KM20616',
                'KM20617',
                'KM20618',
                'KM20619',
                'KM20621',
                'KM20622',
                'KM20623',
                'KM20624',
                'KM20625',
                'KM20626',
                'KM20627',
                'KM20631',
                'KM20632',
                'KM20633',
                'KM20634',
                'KM20635',
                'KM20636',
                'SI20761',
                'SI20762',
                'SI20763',
                'SI20801',
                'SI20764',
                'SI20765',
                'KM20711',
                'KM20712',
                'KM20713',
                'KM20714',
                'KM20715',
                'KM20716',
                'KM20717',
                'KM20718',
                'KM20719',
                'KM20721',
                'KM20722',
                'KM20723',
                'KM20724',
                'KM20725',
                'KM20726',
                'KM20727',
            ],
            'matkul' => [
                'Bahasa Inggris: Reading & Writing',
                'Pendidikan Kewarganegaraan',
                'Algoritma & Struktur Data 1',
                'Logika Matematika',
                'Dasar Pemrograman 1',
                'Pemecahan Masalah Algoritmik',
                'Konsep Sistem',
                'Pengantar Teknologi Informasi',
                'Bahasa Inggris I (Reading + Speaking)',
                'Pancasila',
                'Dasar Manajemen',
                'Pengantar Teknologi Informasi',
                'PPA I (Advance Office)',
                'Algoritma & Struktur Data I',
                'Logika Informatika',
                'Pemrograman I (Java)',
                'Analisis Proses Bisnis',
                'Algoritma & Struktur Data II',
                'Pemrograman II (Objek)',
                'Bahasa Inggris: Presentation',
                'Agama 1',
                'Bahasa Inggris II (Presentation)',
                'Sistem Basis Data',
                'PPA II (SQL)',
                'Konsep Sistem Informasi',
                'Sistem Operasi',
                'Pemrograman Web I',
                'Leadership & Communication Skill',
                'Konsep Sistem Informasi',
                'Algoritma & Struktur Data 2',
                'Dasar Pemrograman 2',
                'Dasar Basis Data',
                'Pengantar Manajemen',
                'Bahasa Inggris: Conversation',
                'Perancangan Basis Data SQL',
                'Probabilitas & Statistika',
                'Aljabar Linier',
                'Jaringan Komputer Dasar',
                'Analisis Proses Bisnis',
                'Perancangan Sistem Informasi 1',
                'Agama 2',
                'Perancangan Basis Data NoSQL',
                'Perancangan Sistem Informasi 2',
                'Kecerdasan Buatan',
                'Interaksi Manusia dan Komputer',
                'Teknologi Web dan Komputasi Terdistribusi',
                'Pengujian & Penerapan Sistem Informasi',
                'Arsitektur Sistem Informasi',
                'Entrepreneurship 2',
                'Research Methods',
                'Artificial Intelligence 2',
                'Augmented Reality',
                'Enterprise Resource Planning (ERP)',
                'Digital Marketing',
                'Business Intelligence',
                'Information Systems Project Management',
                'E-Bisnis',
                'Data Technology, Database and Information Geospatial',
                'Remote Sensing and Geospatial Image Processing',
                'Analysis and Data Geospatial Model',
                'Map Based Programming',
                'Internship*',
                'Entrepreneurship*',
                'Research*',
                'Design and Implementation of System',
                'Data Model Abstraction',
                'Data Analysis',
                'System Integration',
                'System Testing',
                'Platform Preparation and Deployment',
                'Project Management',
                'Creative Marketing',
                'Digital Asset Management',
                'Design and Planning Business',
                'Business Implementation',
                'Developing Business Plan',
                'Business Report',
                'Project Management',
                'Creative Marketing',
                'Digital Asset Management',
                'Research planning and Design',
                'Experiment',
                'Data Analysis',
                'Technical Report Writing',
                'Project Management',
                'Research Ethic',
                'Internship*',
                'Entrepreneurship*',
                'Research*',
                'Final Project',
                'Independent Study*',
                'Campus Teaching*',
                'Design and Implementation of System II',
                'Data Model Abstraction II',
                'Data Analysis II',
                'System Integration II',
                'System Testing II',
                'Platform Preparation and Deployment II',
                'Project Management II',
                'Creative Marketing II',
                'Digital Asset Management II',
                'Design and Planning Business II',
                'Business Implementation II',
                'Developing Business Plan II',
                'Business Report II',
                'Project Management II',
                'Creative Marketing II',
                'Digital Asset Management II',

            ],
            'sks'   => [
                '2',
                '2',
                '4',
                '2',
                '4',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '3',
                '3',
                '3',
                '2',
                '3',
                '3',
                '2',
                '2',
                '2',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '4',
                '4',
                '3',
                '2',
                '2',
                '3',
                '3',
                '2',
                '3',
                '3',
                '3',
                '2',
                '3',
                '3',
                '2',
                '2',
                '3',
                '2',
                '3',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '2',
                '3',
                '3',
                '3',
                '3',
                '3',
                '20',
                '20',
                '20',
                '3',
                '3',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '4',
                '4',
                '3',
                '2',
                '2',
                '2',
                '4',
                '4',
                '4',
                '4',
                '2',
                '2',
                '20',
                '20',
                '20',
                '6',
                '20',
                '20',
                '3',
                '3',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '4',
                '4',
                '3',
                '2',
                '2',
                '2',
            ],
            'semester' =>[
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '4',
                '4',
                '4',
                '4',
                '4',
                '4',
                '4',
                '4',
                '5',
                '5',
                '5',
                '5',
                '5',
                '5',
                '5',
                '6',
                '6',
                '6',
                '6',
                '6',
                '6',
                '6',
                '6',
                '7',
                '7',
                '7',
                '7',
                '7',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
                '3',
                '1',
                '4',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
                '7',
                '5',
                '8',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
                '-',
                '-',
                '-',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
                '-',
                '-',
                '-',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
                '-',
                '-',
                '-',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
            ],
        ];

        for ($i=0;$i<114;$i++) {
            $semseter = mt_rand(1,2);

            DB::table('mata_kuliah')->insert([
                'kode_matkul' => $m['kode'][$i],
                'nama_matkul' => $m['matkul'][$i],
                'sks' => $m['sks'][$i],
                'semester'    => $m['semester'][$i],
                'jurusan' => 'SI'
            ]);
        }
    }    
}
