<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MatakuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      
        $m = [
            'kode' => [
                'IF-18101',
                'IF-18102',
                'IF-18103',
                'IF-18104',
                'IF-18105',
                'IF-18106',
                'IF-18107',
                'IF-18108',
                'IF101',
                'IF102',
                'IF103',
                'IF104',
                'IF105',
                'IF106',
                'KU101',
                'KU102',
                'IF-18201',
                'IF-18202',
                'IF-18203',
                'IF-18204',
                'IF-18205',
                'IF-18206',
                'IF-18207',
                'IF201',
                'IF202',
                'IF203',
                'IF204',
                'IF205',
                'KU201',
                'KU202',
                'IF301',
                'IF302',
                'IF303',
                'IF304',
                'IF305',
                'IF306',
                'KU301',
                'IF401',
                'IF402',
                'IF403',
                'IF404',
                'IF405',
                'IF406',
                'KU401',
                'IF20501',
                'IF20511',
                'IF20512',
                'IF20514',
                'IF20515',
                'IF20516',
                'IF20521',
                'IF20522',
                'IF20523',
                'IF20525',
                'IF20526',
                'IF20527',
                'IF20528',
                'IF20661',
            ],
            'matkul' => [
                'Bahasa Inggris I (Reading+Speaking)',
                'Pancasila',
                'Dasar Manajemen Umum',
                'Pengantar Teknologi Informasi',
                'PPA I (Advanced Office)',
                'Algoritma & Struktur Data I',
                'Logika Informatika',
                'Pemrograman I (Java)',
                'Logika Matematika',
                'Algoritma & Struktur Data 1',
                'Dasar Pemrograman 1	',
                'Penyelesaian Masalah Algoritmik',
                'Pengantar Teknologi Informasi',
                'Teknologi Web',
                'Bahasa Inggris: Reading & Writing',
                'Pendidikan Kewarganegaraan',
                'Bahasa Inggris II (Presentation)',
                'Leadership & Communication Skill',
                'Sistem Basis Data',
                'PPA II (SQL)',
                'Arsitektur Komputer',
                'Sistem Operasi',
                'Pemrograman Web I',
                'Algoritma & Struktur Data 2',
                'Dasar Pemrograman 2',
                'Dasar Basis Data',
                'Matematika Diskrit',
                'Sistem Operasi',
                'Bahasa Inggris: Presentation',
                'Agama 1',
                'Aljabar Linier',
                'Probabilitas & Statistika',
                'Paradigma Pemrograman (OO & Fungsional)',
                'Rekayasa Perangkat Lunak',
                'Jaringan Komputer Dasar',
                'Desain Web',
                'Bahasa Inggris: Conversation',
                'Rekayasa Protokol',
                'Pemrograman Basis Data',
                'Kriptografi',
                'Komputasi Terdistribusi',
                'Kecerdasan Buatan',
                'Pemrograman Mobile',
                'Agama 2',
                'Research Methods',
                'Cryptography',
                'Security Fundamental',
                'Mobile & Cloud Security',
                'Penetration Testing',
                'Incident Response & Digital Forensic	',
                'Natural Language Processing (NLP)	',
                'Image Processing	',
                'IoT Concept & Microcontroller	',
                'Adhoc Networks	',
                'Data Science	',
                'Electronic Circuit	',
                'Augmented Reality	',
                'Internship *',
            ],
            'sks'   => [
                '2',
                '4',
                '4',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '3',
                '3',
                '3',
                '2',
                '2',
                '2',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '4',
                '4',
                '3',
                '3',
                '2',
                '2',
                '2',
                '2',
                '3',
                '4',
                '3',
                '3',
                '3',
                '2',
                '3',
                '3',
                '3',
                '2',
                '4',
                '3',
                '2',
                '2',
                '3',
                '4',
                '3',
                '3',
                '4',
                '2',
                '2',
                '3',
                '3',
                '2',
                '3',
                '2',
                '2',
            ],
            'Semester' =>[
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '1',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '2',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '3',
                '4',
                '4',
                '4',
                '4',
                '4',
                '4',
                '4',
                '4',
                '5',
                '5',
                '5',
                '5',
                '5',
                '5',
                '5',
                '6',
                '6',
                '6',
                '6',
                '6',
                '6',
                '6',
                '6',
                '7',
                '7',
                '7',
                '7',
                '7',
                '7',
                '7',
                '7',
                '8',
                '8',
                '8',
                '8',
            ]
        ];

        for ($i=0;$i<58;$i++) {
            $semseter = mt_rand(1,2);

            DB::table('mata_kuliah')->insert([
                'kode_matkul' => $m['kode'][$i],
                'nama_matkul' => $m['matkul'][$i],
                'sks'         => $m['sks'][$i],
                'Semester'    => $m['Semester'][$i],
                'jurusan' => 'IF'
            ]);
        }
    }
}

